- hosts: localhost
  connection: local
  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "aws-devops-kaypair"
      instance_type: t3.micro
      security_group: allow-all-sg
      region: us-east-1a
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - { image: "ami-0fd3ac4abb734302a", name: "manage-node-1" } # Update AMI ID according 
      - { image: "ami-0fd3ac4abb734302a", name: "manage-node-2" } # to your account
      - { image: "ami-0fd3ac4abb734302a", name: "manage-node-3" }
      